### ISSUE TITLE
yolo instance segmentation format?

### ISSUE THREAD

**Issue by mhyeonsoo** [akashAD98/YOLOV8_SAM#3]
Hi again,

Thanks for implementing annotation generation scripts.
After running the code to generate the .txt mask label, I tried to import image/label/labelmap to see if the annotation is generated well.
However, it seemed like the annotation is somewhat messed up.

I checked with Roboflow tool, and could see the image like below.
![image](https://user-images.githubusercontent.com/32179857/236977416-b0f36119-3d62-41a3-b10f-89658afd6953.png)

Have you tried to train the yolo model with the generated labels?

Thank you so much,

**Comment by akashAD98** [comment]
@mhyeonsoo yes i tried it able to train the model also? are you still getting issue?

**Comment by mhyeonsoo** [comment]
@akashAD98 
Yes, still getting an issue. Can you show me a sample txt file for generated annotation?

**Comment by akashAD98** [comment]
@mhyeonsoo sorry, i was latly busy in work,
can you try visulise_inference.py to check your annotations? also the script is working fine.
if you want to try google collab you can also check my .ipynb file . & please let me knoe

**Comment by mhyeonsoo** [comment]
I'll try with that script. Thanks!

**Comment by akashAD98** [comment]
@mhyeonsoo try it & let me know if you get any problems. im closing this issue right now ,open it agin if you get issue
