### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 1012537710** [akashAD98/YOLOV8_SAM#4]
Thank you for the code. It is very effective. But I encountered a bug when I run main.py. The bug is shown as follows:
---NameErrror: name 'show_mask' is not defined;
---NameErrror: name 'show_box' is not defined.
I looked for the code, and it doesn't seem to be defined.

**Comment by akashAD98** [comment]
@1012537710 i have updated main.py & added a function for visualization, also check i have updated my readme. so directly you can visualise mask using inference_image.py

**Comment by 1012537710** [comment]
@akashAD98  Thank you for your response. Your code is extremely helpful to me. Thank you for your efforts. 👍
