### ISSUE TITLE
where is best.pt model

### ISSUE THREAD

**Issue by ibtehajali67** [akashAD98/YOLOV8_SAM#5]
I am facing problem to find that model

**Comment by akashAD98** [comment]
@ibtehajali67 best.pt file is your custom model, which is trained by you 
oterwise you can use yolov8.pt  https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8s.pt

**Comment by ibtehajali67** [comment]
@akashAD98 I have used  `model=YOLO('yolov8n-seg.pt')` but some of result are good and other have some problem.
**Good Result**
<img width="204" alt="good_result" src="https://github.com/akashAD98/YOLOV8_SAM/assets/49198838/d05899f7-ebce-4ba3-b2e9-e90fbb14c1ad">
**Bed Result**
<img width="169" alt="bed_result" src="https://github.com/akashAD98/YOLOV8_SAM/assets/49198838/455d63f0-15c5-401c-878b-08edb9806d30">
<img width="228" alt="bed_result_1" src="https://github.com/akashAD98/YOLOV8_SAM/assets/49198838/c22bc075-3835-46bc-bc04-d1d53a54b890">

**Comment by akashAD98** [comment]
@ibtehajali67 sorry for late reply, you can try **vit_l** model of sam & also try larger model of yolov8 so it will detect object easily
