### ISSUE TITLE
name 'predictor' is not defined

### ISSUE THREAD

**Issue by Kr-Sheshank** [akashAD98/YOLOV8_SAM#6]
![Screenshot from 2023-06-05 14-54-33](https://github.com/akashAD98/YOLOV8_SAM/assets/115135568/e79a9e7e-3de7-4d88-9dc3-13bdbe344941)

I m trying your multiobject segmentation code using yolov8n.pt model, but I m getting the error  "name 'predictor' is not defined" Also, yolov8 is not detecting any object; I m using an image of a person for the test.  
Can you please tell me what I m doing wrong?

**Comment by akashAD98** [comment]
@Kr-Sheshank  i fixed it ,you can check now
