### ISSUE TITLE
did you try this project on labelstudio?

### ISSUE THREAD

**Issue by widedh** [akashAD98/YOLOV8_SAM#7]
Hello, 

I want to train the model on a custom dataset. To do I have to annotate some images on labelstudio. Did you try to integrate this project on labelstudio?

**Comment by akashAD98** [comment]
@widedh no I haven't integrated it, what you can do is, do the annotations using this code, & cross verify the annotionas which are not correct, then you can use any tool to do it manually, but it's not giving 100% accuracy to all images.
